# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-12 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=0, verbose_name='\u6536\u85cf\u6570'),
        ),
    ]
