# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='\u5168\u56fd\u77e5\u540d', max_length=20, verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
