# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-20 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_id',
            field=models.IntegerField(default=0, verbose_name='\u7528\u6237\u6536\u85cfid'),
        ),
    ]
