# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-08 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_categ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categ',
            new_name='category',
        ),
    ]
