# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_time',
            field=models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u65f6\u957f(min)'),
        ),
    ]
